posts/apiposts/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^api/$', views.allposts, name='api-all' ),   # all posts from API
    url(r'^api/(?P<postid>\d+)', views.getpost, name="api-id"),   # one specific post from API
    url(r'^api/user/(?P<userid>\d+)', views.getuser, name="api-user"),  # a user's posts url from API

    url(r'^db/$', views.getposts_from_model, name="db-all"),  # all posts url from DB
    url(r'^db/(?P<postid>\d+)', views.get_post_by_id, name="db-id"),  # one specific post url from DB
    url(r'^new/$', views.post_form, name="new-post"),

    url(r'^list/$', views.PostListView.as_view(), name='posts-list'),  # list from posts from listview

]

posts/posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('apiposts.urls', namespace="posts"), name="posts"),   # apiposts url address
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="index"),  # home page templates
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^soap/', include('soapws.urls', namespace='soapws')),
]

posts/soapws/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^showusers', views.show_users, name='all-users'),
    url(r'^createuser', views.create_user, name='create-user'),
]

posts/apiposts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User



class Posts(models.Model):
    userId = models.ForeignKey(User)
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=512)

    def __str__(self):
        return str(self.title)



class Comments(models.Model):
    postId = models.ForeignKey(Posts)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    body = models.TextField(max_length=512)
    email = models.EmailField()

    def __str__(self):
        return str(self.name)

posts/soapws/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

posts/apiposts/forms.py
from django.forms import ModelForm
from . models import Posts,Comments


class PostsForm(ModelForm):
        class Meta:
            model = Posts
            fields = [ 'title', 'body']


class CommentsForm(ModelForm):
        class Meta:
            model = Comments
            fields = [ 'name', 'body', 'email']

posts/soapws/forms.py
from django import forms


class CreateUserForm(forms.Form):
    firstName = forms.CharField(label='First Name', max_length=100, required=True)
    lastName = forms.CharField(label='Last Name', max_length=100, required=True)

posts/apiposts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
import json
import urllib2
from . models import Posts, Comments
from . forms import PostsForm, CommentsForm


# ------------------- Views tha get data from API------------------------------------------
def allposts(request):
	data = json.load(urllib2.urlopen('http://jsonplaceholder.typicode.com/posts'))
	context = {'data': data}
	return render(request, 'apiposts/allposts-api.html', context)


def getpost(request, postid):
	post = json.load(urllib2.urlopen('http://jsonplaceholder.typicode.com/posts/' + postid))
	comments = json.load(urllib2.urlopen('http://jsonplaceholder.typicode.com/posts/' + postid + '/comments'))
	context = {'post': post, 'comments': comments, 'api': True}
	return render(request, 'apiposts/post.html', context)


def getuser(request, userid):
	user = json.load(urllib2.urlopen('http://jsonplaceholder.typicode.com/users/' + userid))
	user_posts = json.load(urllib2.urlopen('http://jsonplaceholder.typicode.com/posts?userId=' + userid))
	context = {'user': user, 'user_posts': user_posts}
	return render(request, 'apiposts/user.html', context)

# ------------------- Views tha get data from DB------------------------------------------

@login_required
def getposts_from_model(request):
	data = Posts.objects.all()
	context = {'data': data}
	return render(request, 'apiposts/allposts-db.html', context)


@login_required
def post_form(request):
	if request.method == 'GET':
		form = PostsForm()
	else:
		form = PostsForm(request.POST)
		if form.is_valid():
			title = form.cleaned_data['title']
			body = form.cleaned_data['body']
			post = Posts.objects.create(title=title, body=body, userId=request.user)
			return HttpResponseRedirect("/apiposts/dbdata/")

	return render(request, 'apiposts/newpost.html', {'form': form,})


@login_required
def get_post_by_id(request,postid):
	data = Posts.objects.get(id=postid)
	comments = Comments.objects.filter(postId=postid)
	context = {'post': data, 'comments': comments, 'api': False}
	return render(request, 'apiposts/post.html', context)


class PostListView(ListView):
	model = Posts

posts/soapws/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import CreateUserForm


# Create your views here.
from django.shortcuts import render
from suds.client import Client
soap_client = Client('http://10.100.51.100:8080/soapwebsrv/sakilaws?WSDL')


def show_users(request):
	results = soap_client.service.actors()
	context = {'results':results, }
	return render(request, 'soapws/allusers.html', context)


def create_user(request):
	if request.method == 'GET':
		form = CreateUserForm()
	else:
		form = CreateUserForm(request.POST)
		if form.is_valid():
			firstName = form.cleaned_data['firstName']
			lastName = form.cleaned_data['lastName']
			result = soap_client.service.createactor(firstName, lastName)
			if result:
				return HttpResponseRedirect(reverse('soapws:all-users'))
			else:
				return HttpResponse("User Not Created")

	return render(request, 'soapws/createuser.html', {
	   'form': form,
	})

posts/apiposts/templates/apiposts/allposts-api.html
{% extends 'base.html' %}

{% block body_block %}
<ul id="results">
    {% for post in data %}
     <li> <a href = "{% url 'posts:api-id' post.id %}"> ID: {{post.id}} - Title : {{ post.title}} </a> </li>
    {% endfor %}

</ul>
{% endblock %}

posts/apiposts/templates/apiposts/allposts-db.html
{% extends 'base.html' %}

{% block body_block %}
<ul id="results">
    {% for post in data %}
     <li> <a href = "{% url 'posts:db-id' post.id %}"> ID: {{post.id}} - Title : {{ post.title}} </a> </li>
    {% endfor %}

</ul>
{% endblock %}

posts/apiposts/templates/apiposts/allposts.html
{% extends 'base.html' %}

{% block body_block %}
<ul id="results">
    {% for post in data %}
     <li> <a href = "/apiposts/{{post.id}}"> ID: {{post.id}} - Title : {{ post.title}} </a> </li>
    {% endfor %}

</ul>
{% endblock %}

posts/apiposts/templates/apiposts/newpost.html
{% extends 'base.html' %}

{% block body_block %}

<form action='.' method='post'>{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Submit' />
</form>


{% endblock %}

posts/apiposts/templates/apiposts/post.html
{% extends 'base.html' %}

{% block body_block %}
    <ul id="results">
    <h3> Post </h3>
    {% if api %}
        <li> <a href = "{% url 'posts:api-user' post.userId %}"> User Id : {{post.userId}} </a> </li>
    {% endif %}
    <li> Post Id : {{post.id}} </li>
     <li> Title : {{ post.title}} </li>
    <li> Body : {{ post.body}} </li>
    </ul>

    <h3> Comments </h3>


    {% for comment in comments %}
        <ul id="comment" >
            <b> Comment number {{ forloop.counter }}</b>
             <li>  Body : {{ comment.body }} </li>
             <li> Name: {{ comment.name}} -- Email: {{comment.email}} </li>
        </ul>
    {% endfor %}


{% endblock %}

posts/apiposts/templates/apiposts/posts_list.html
{% extends 'base.html' %}

{% block body_block %}
<h1>Posts</h1>
<ul>
{% for post in object_list %}
     <li> <a href = "{% url 'posts:db-id' post.id %}"> ID: {{post.id}} - Title : {{ post.title}} </a> </li>
{% empty %}
    <li>No posts yet.</li>
{% endfor %}
</ul>

{% endblock %}

posts/apiposts/templates/apiposts/user.html
{% extends 'base.html' %}

{% block body_block %}
    <ul id="results">
    <h3> User Info </h3>
    <li> name : {{user.name}} </li>
    <li> username : {{user.username}} </li>
    <li> email : {{user.email}} </li>
    <li> phone : {{user.phone}} </li>
    </ul>

    <h3> Posts by {{user.name}} </h3>


    {% for post in user_posts %}
        <ul id="comment" >
            <b> Post number {{ forloop.counter }}</b>
             <li> Title : {{ post.title}} </li>
            <li> Body : {{ post.body}} </li>
        </ul>
    {% endfor %}


{% endblock %}

posts/soapws/templates/soapws/allusers.html
{% extends 'base.html' %}

{% block body_block %}
<h1> Soap WS Users </h1>

<table class="table table-striped">
   <tr class="active">
   <th class="active" >First Name</th>
   <th class="active">Last Name</th>
 </tr>
{% for result in results %}
   <tr class="active">
       <td class="active"> {{result.firstName}} </td>
       <td class="active"> {{result.lastName}} </td>
   <tr/>
{% endfor %}

   </table>
<br>

<a href="{% url 'soapws:create-user' %}"> Create new User </a>

{% endblock %}

posts/soapws/templates/soapws/createuser.html
{% extends 'base.html' %}

{% block body_block %}

<form action='{% url 'soapws:create-user' %}' method='post'>{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Submit' />
</form>

{% endblock %}

posts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>First exercise in Django </title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Home</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <li><a href="{% url 'posts:api-all' %}">API Posts</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'posts:db-all' %}">DB Posts</a></li>
                <li><a href="{% url 'soapws:all-users' %}">SOAP Users</a></li>
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Register</a></li>
                <li><a href="{% url 'auth_login'%}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}{% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
                {% block content %}{% endblock %}
                </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

posts/templates/index.html
{% extends 'base.html' %}

{% block body_block %}
    <h3> Exercise for Department of Informatics and Telematics</h3>
{% endblock %}